"""add_fiscal_year_tracking

Revision ID: bd48873cbc1f
Revises: f8d59caa28e9
Create Date: 2026-08-07 12:58:40.816711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd48873cbc1f'
down_revision: Union[str, Sequence[str], None] = 'f8d59caa28e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_matches', sa.Column('matched_document_id', sa.String(length=20), nullable=True))
    op.add_column('submissions', sa.Column('fiscal_year', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('submissions', 'fiscal_year')
    op.drop_column('budget_matches', 'matched_document_id')
    # ### end Alembic commands ###
