"""initial_schema

Revision ID: f8d59caa28e9
Revises: 
Create Date: 2026-08-06 14:44:03.759057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8d59caa28e9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('budget_documents',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_hash', sa.String(length=64), nullable=False),
    sa.Column('fiscal_year', sa.String(length=20), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=False),
    sa.Column('size_mb', sa.Float(), nullable=False),
    sa.Column('total_pages', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('uploading', 'ready', 'failed', 'archived', name='documentstatus'), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_documents_file_hash'), 'budget_documents', ['file_hash'], unique=True)
    op.create_table('participation_sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('pages_parsed', sa.Integer(), nullable=False),
    sa.Column('points_extracted', sa.Integer(), nullable=False),
    sa.Column('points_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.String(length=20), nullable=False),
    sa.Column('ward', sa.String(length=100), nullable=False),
    sa.Column('channel', sa.Enum('sms', 'ussd', 'whatsapp', 'web_form', 'baraza', 'voice', 'image', name='channel'), nullable=False),
    sa.Column('citizen_input', sa.Text(), nullable=False),
    sa.Column('original_language', sa.String(length=30), nullable=False),
    sa.Column('translated_input', sa.Text(), nullable=True),
    sa.Column('sector', sa.String(length=50), nullable=True),
    sa.Column('sub_sector', sa.String(length=80), nullable=True),
    sa.Column('classification_confidence', sa.Float(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=20), nullable=False),
    sa.Column('matched_line_id', sa.String(length=50), nullable=True),
    sa.Column('matched_sector', sa.String(length=50), nullable=True),
    sa.Column('matched_description', sa.Text(), nullable=True),
    sa.Column('matched_amount_ksh', sa.Integer(), nullable=True),
    sa.Column('source_page', sa.Integer(), nullable=True),
    sa.Column('budget_result', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('matched', 'partial', 'ignored', name='matchstatus'), nullable=False),
    sa.Column('similarity_score', sa.Float(), nullable=False),
    sa.Column('participation_boost', sa.Float(), nullable=False),
    sa.Column('boosted_score', sa.Float(), nullable=False),
    sa.Column('simplified', sa.Text(), nullable=True),
    sa.Column('key_points', sa.Text(), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('alternative_matches', sa.Text(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('submission_id')
    )
    op.create_table('participation_matches',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('submission_id', sa.String(length=20), nullable=False),
    sa.Column('session_id', sa.String(length=36), nullable=True),
    sa.Column('point_id', sa.String(length=20), nullable=False),
    sa.Column('point_text', sa.Text(), nullable=True),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('boost_factor', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['participation_sessions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation_matches')
    op.drop_table('budget_matches')
    op.drop_table('submissions')
    op.drop_table('participation_sessions')
    op.drop_index(op.f('ix_budget_documents_file_hash'), table_name='budget_documents')
    op.drop_table('budget_documents')
    # ### end Alembic commands ###
